### ISSUE TITLE
Version `[1.19.3] 1.0.1/2` Should not be marked compatible with `1.19.2` in modrinth page

### ISSUE THREAD

**Issue by Vigilans** [mineblock11/Illagers-Love-Armor#2]
https://modrinth.com/mod/illagers-love-armor/version/1.0.1+1.19.3

It is marked with minecraft version `1.19.2—1.19.3`, However downloaded jar is only compatible with `1.19.3`:

```json
  "depends": {
    "fabricloader": ">=0.14.10",
    "fabric": "*",
    "minecraft": "1.19.3",
    "minelib": "*"
  }
```

This will make auto mod updater downloads a jar that is not launchable in 1.19.2.

**Comment by mineblock11** [comment]
Thanks for reporting. Fixed
